Admin Login
csys-fresher-batch-2021/movieratingapp-core-kannan pull request #10
Opened 2021-06-08 09:00 UTC by KANNAN84-hash

Here I have done Admin Login feature for Admin to login using email and password

2021-06-08 09:16 UTC, csys-fresher-batch-2021 commented on sql/movies.sql
> +				  role varchar(255) not null check(role in('Admin','User')));
Prefer - ADMIN, USER

2021-06-08 09:16 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/dao/AdminDAO.java
> +public class AdminDAO {
UserDAO

2021-06-08 09:16 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/dao/AdminDAO.java
> +	public static Users findByGmailAndPassword(String email, String password) throws DBException, AdminLoginException {
findByEmailAndPassword

2021-06-08 09:18 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/model/Users.java
> +public class Users {
User user  = new User(1,'Kannan'). Rename Users to user.

2021-06-08 09:18 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/service/AdminService.java
> +public class AdminService {
UserService

2021-06-08 09:18 UTC, csys-fresher-batch-2021 requested changes
Changes Requested.

2021-06-09 13:04 UTC, csys-fresher-batch-2021 approved these changes

2021-06-09 14:29 UTC, merged

2021-06-09 14:29 UTC, KANNAN84-hash commented
Here I have completed the Admin login feature .