Feature : Display movie detail
csys-fresher-batch-2021/movieratingapp-core-kannan pull request #8
Opened 2021-06-02 09:03 UTC by KANNAN84-hash

#### Here I have Displayed the movie Details for the users

2021-06-02 09:49 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/dao/MovieDAO.java
> +				mov = new Movie(id, name, getStartDate, active, getEndDate);
Movie mov = new Movie();  
Reduce the scope of the variable

2021-06-02 09:50 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/exception/ConnectionException.java
> +public class ConnectionException extends Exception {
extends RuntimeException

To avoid throws ConnectionException

2021-06-02 09:51 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/dao/MovieDAO.java
> +			throw new DAOException(e, "Unable to display movies");
DBException (or)
PersistenceException

2021-06-02 09:51 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/model/Movie.java
> +	private LocalDate startDate;
Use releaseDate instead of startDate

2021-06-02 09:52 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/util/ConnectionUtil.java
> +	private static final String DRIVER_CLASS_NAME = "org.postgresql.Driver";
Environment Variables.
Avoid exposing DB credentials in code.

2021-06-02 09:53 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/util/ConnectionUtil.java
> +			throw new ConnectionException(e, "Unble to Connect");
Fix the spelling.

2021-06-02 09:53 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/util/ConnectionUtil.java
> +			rs.close();
rs.close = Chances of NullPointerException . Add Null Check.
if(rs != null) {
rs.close();
}

2021-06-02 09:54 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/util/ConnectionUtil.java
> +			throw new DAOException(e, "Unable to close DAO");
Suppress exception. Don't throw.

2021-06-02 09:54 UTC, csys-fresher-batch-2021 commented on src/test/java/in/kannan/TestClass.java
> +public class TestClass {
Use proper Class Name

2021-06-02 09:54 UTC, csys-fresher-batch-2021 requested changes
Added my review comments.

2021-06-03 07:28 UTC, KANNAN84-hash commented on src/test/java/in/kannan/ServiceTest.java
> +public class ServiceTest {
change class name -MovieServiceTest

2021-06-03 07:29 UTC, KANNAN84-hash commented on src/main/java/in/kannan/util/ConnectionUtil.java
> +			ps.close();
add null check

2021-06-03 07:32 UTC, KANNAN84-hash commented on sql/movies.sql
> +					end_date date not null, primary key(movie_id)
remove not null for end date,use serial for movie id column, status should contain dfault value true

2021-06-04 06:11 UTC, csys-fresher-batch-2021 commented on src/main/java/in/kannan/model/Movie.java
> +	public LocalDate getStartDate() {
wrong setter/getters for releaseDate. Regenerate for releaseDate field.

2021-06-04 08:55 UTC, merged